USER_RECORDS = [
        {
            "company_lead_name": "Velo Labs",
            "industry": "Blockchain",
            "location": "Thailand",
            "services": "Non-custodial Wallet, Cryptocurrency Management, Token Swaps",
            "project_description": "Built Orbit Wallet - a non-custodial wallet enabling users to seamlessly manage, transfer, and swap cryptocurrencies and tokens. Also facilitates launching discount campaigns and token airdrops, with crypto exchange integration.",
            "background": "Web3-based liquidity and settlement network focused on Southeast and Pacific partners, dedicated to connecting businesses with global funds and enhancing global financial accessibility.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Blockchain Development, Wallet Development, DeFi Integration",
            "description_company_outsource": "Velo Labs develops a Web3-based liquidity and settlement network. Supported by Stellar Network and CP Group, focusing on Southeast and Pacific partners.",
        },
        {
            "company_lead_name": "KLDX",
            "industry": "Blockchain",
            "location": "Malaysia",
            "services": "Digital Assets Platform, Security Token Offering, Asset Tokenization",
            "project_description": "Built KLDX STO platform enabling conversion of traditional securities into digital tokens for easier blockchain-based trading. Facilitates issuance and management of tokenized securities for uniquely curated alternative investment assets.",
            "background": "Initial Exchange Offering (IEO) platform regulated and registered with the Securities Commission Malaysia (SC). Democratizes investors' access to private market assets and helps businesses raise funds up to RM100 million.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Blockchain Development, Tokenization, Compliance Management",
            "description_company_outsource": "KLDX is a regulated IEO platform backed by Malaysia government, enabling security token issuance and digital asset trading.",
        },
        {
            "company_lead_name": "Gambit",
            "industry": "Blockchain",
            "location": "Malaysia",
            "services": "Digital Asset Custody, Secure Storage, Cold Wallet Solutions",
            "project_description": "Built government-licensed digital asset custody platform providing businesses with secure solutions for managing digital assets. Employs robust storage mechanisms utilizing both hot and cold wallets for asset protection.",
            "background": "Blockchain infrastructure service provider working closely with enterprises, institutions and regulators. Aims to become a regulated and holistic digital assets ecosystem.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Blockchain Development, Custody Solutions, Security Infrastructure",
            "description_company_outsource": "GamBit is backed by Malaysia government and specializes in regulated digital asset management and ecosystem development.",
        },
        {
            "company_lead_name": "Cardano",
            "industry": "Blockchain",
            "location": "Switzerland",
            "services": "Wallet Integration, Fiat-to-Crypto Gateway, DeFi Access",
            "project_description": "Collaborated with Cardano to integrate Banxa, a leading fiat-to-crypto gateway, into the Yoroi Wallet, enabling users to conveniently buy and sell cryptocurrencies directly within the wallet.",
            "background": "Layer 1 proof-of-stake blockchain platform founded on peer-reviewed research and developed through evidence-based methods. Combines pioneering technologies to provide unparalleled security and sustainability.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Wallet Development, DeFi Integration, Payment Gateway",
            "description_company_outsource": "Cardano is a top Layer 1 blockchain platform with emphasis on peer-reviewed research and sustainable development.",
        },
        {
            "company_lead_name": "RHT",
            "industry": "Blockchain",
            "location": "Singapore",
            "services": "NFT Marketplace, Digital Art Platform, KYC/KYT Enhancement",
            "project_description": "Built Verdant - multiple NFT marketplaces empowering users to seamlessly buy, sell, bid and burn NFTs with enhanced KYC/KYT protocols.",
            "background": "Digital art and collectibles platform focused on decentralized marketplace for tokenized assets.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "51-200 Employees",
            "client_min": 51,
            "client_max": 200,
            "services_company_outsource": "NFT Marketplace Development, Compliance Integration",
            "description_company_outsource": "RHT operates a decentralized NFT marketplace on Polygon network.",
        },
        {
            "company_lead_name": "Playbux",
            "industry": "Blockchain",
            "location": "Thailand",
            "services": "Play-to-Earn Platform, Blockchain Gaming, NFT Integration",
            "project_description": "Developed Conquer to Earn - a Play-to-Earn platform hosting a strategic game where participants representing different nationalities use tokens to acquire and defend territories. Winners receive exclusive prizes.",
            "background": "Initially established on BNB chain with support from Binance Labs. Seamlessly integrates e-commerce, blockchain technology, and virtual communities with services like Shop to Earn, Walk to Earn, Watch to Earn, and Play to Earn.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Game Development, Blockchain Integration, Play-to-Earn Mechanics",
            "description_company_outsource": "Playbux is a BNB-based platform backed by Binance Labs, facilitating user earnings through innovative e-commerce and gaming programs.",
        },
        {
            "company_lead_name": "Ultorex",
            "industry": "Blockchain",
            "location": "Turkey",
            "services": "Centralized Exchange, Cryptocurrency Trading, Secure Transaction System",
            "project_description": "Delivered one of the leading centralized crypto trading platforms in Turkey. Platform provides a secure transaction system based on 2FA using multiple person signature methodologies. Can handle 100,000 transactions per second.",
            "background": "Cryptocurrency exchange platform empowering Turkish investors to participate in the digital asset revolution with confidence and agility.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Exchange Development, Security Infrastructure, High-Performance Trading",
            "description_company_outsource": "Leading centralized crypto trading platform in Turkey with high-capacity transaction processing.",
        },
        {
            "company_lead_name": "Gnoland",
            "industry": "Blockchain",
            "location": "United States",
            "services": "Decentralized Exchange, DeFi Platform, Liquidity Management",
            "project_description": "Built Onbloc Gno - the first decentralized exchange (DEX) on Gnoland providing users with a simplified, secure and liquid DeFi platform. Uses Concentrated Liquidity Market Maker (CLMM) model for competitive pricing.",
            "background": "Blockchain platform designed to improve smart contract efficiency and scalability through parallel execution and better resource utilization, suitable for high-performance decentralized applications.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "DEX Development, DeFi Infrastructure, Liquidity Protocols",
            "description_company_outsource": "Gnoland is a blockchain platform focusing on smart contract efficiency and scalability for decentralized applications.",
        },
        {
            "company_lead_name": "Hedera",
            "industry": "Blockchain",
            "location": "Unspecified",
            "services": "DAO Platform, Governance Protocols, Token-based Decision Making",
            "project_description": "Built EasiDAO - fostering a democratic environment on Hedera where users can actively participate in decision-making by voting on initiatives using Hedera's native HBAR tokens. Embodies decentralized and participatory governance principles.",
            "background": "Layer 1 blockchain using hashgraph technology, offering high transaction speeds and low energy consumption. Supports various applications such as payments, identity services, and tokenization.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "DAO Development, Governance Infrastructure, Blockchain Integration",
            "description_company_outsource": "Hedera is a top Layer 1 blockchain with hashgraph technology, providing high transaction speeds and low energy consumption.",
        },
        {
            "company_lead_name": "Bitkub",
            "industry": "Blockchain",
            "location": "Thailand",
            "services": "Learning System, Education Platform, NFT Certificate Issuance",
            "project_description": "Built Learn and Earn Learning System enabling academic organizations to sell courses to learners. Users' academic results are issued as NFTs through the blockchain network, enhancing reliability and accuracy of credentials.",
            "background": "Thailand's largest cryptocurrency exchange regulated by Thailand's Securities and Exchange Commission (SEC). Issues NFT certificates for learners who complete courses.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Education Platform Development, Blockchain Integration, NFT Systems",
            "description_company_outsource": "Bitkub is Thailand's largest regulated cryptocurrency exchange backed by Thailand government, offering innovative education and training services.",
        },
        {
            "company_lead_name": "Aptos",
            "industry": "Blockchain",
            "location": "United States",
            "services": "SDK Development, Game Development Tools, Blockchain Integration",
            "project_description": "Developed Aptos Unreal SDK empowering developers to build high-quality blockchain games on Unreal Engine 5, specifically serving AAA game projects.",
            "background": "Layer 1 blockchain focusing on scalability and reliability, using the Move programming language for enhanced smart contract development.",
            "website_outscore_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "SDK Development, Game Development, Blockchain Integration",
            "description_company_outsource": "Aptos is a top Layer 1 blockchain focusing on scalability with Move programming language for smart contract development.",
        },
        {
            "company_lead_name": "SUI",
            "industry": "Blockchain",
            "location": "Switzerland",
            "services": "Game SDK, Unity/Unreal SDK, Blockchain Integration",
            "project_description": "Developed Sui Unity/Unreal SDK enabling game developers to integrate Sui blockchain into their game development workflows on both Unity and Unreal platforms.",
            "background": "Layer 1 blockchain supporting creation of rich and dynamic on-chain assets with instant settlement and high throughput. Highly scalable and secure platform making digital asset ownership accessible to everyone.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Game SDK Development, Blockchain Integration",
            "description_company_outsource": "SUI is a Layer 1 blockchain offering instant settlement, high throughput, and dynamic on-chain asset creation.",
        },
        {
            "company_lead_name": "Hedera",
            "industry": "Blockchain",
            "location": "Unspecified",
            "services": "Key Management, Security Infrastructure, Identity Management",
            "project_description": "Built Hedera Key Management Platform - a security information management platform for managing wallets (private keys) and environment variables with secure multi-key authentication.",
            "background": "Layer 1 blockchain using hashgraph technology with high transaction speeds and low energy consumption. Supports payments, identity services, and tokenization applications.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Security Infrastructure, Key Management Systems, Identity Management",
            "description_company_outsource": "Hedera provides Layer 1 blockchain with hashgraph technology for secure and efficient transaction processing.",
        },
        {
            "company_lead_name": "DOP",
            "industry": "Blockchain",
            "location": "Israel",
            "services": "NFT Marketplace, Privacy-Focused Trading, Decentralized Platform",
            "project_description": "Built DOP NFT Marketplace - a secure and privacy-focused NFT trading platform powered by the DOP protocol. Allows users to mint, buy, sell, and trade NFTs using ZK-SNARKs for privacy and internal accounts for secure data management.",
            "background": "Data Ownership Protocol restoring control to users over their own data in the Web3 economy. Protocol enables selective transparency of user data, empowering people to own and control their financial information.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "51-200 Employees",
            "client_min": 51,
            "client_max": 200,
            "services_company_outsource": "NFT Marketplace Development, Privacy Technology, Data Management",
            "description_company_outsource": "DOP is a privacy-focused protocol enabling users to own and control their financial data in the Web3 economy.",
        },
        {
            "company_lead_name": "Hedera",
            "industry": "Blockchain",
            "location": "Unspecified",
            "services": "Learning Management System, Blockchain Education, Certificate Verification",
            "project_description": "Built Hedera Learning Management System - a platform to share free Hedera courses. After finishing courses, users can take tests and receive certificates issued as NFTs through the blockchain network, enhancing reliability and accuracy.",
            "background": "Layer 1 blockchain using hashgraph technology offering high transaction speeds and low energy consumption. Supports various applications including identity services and tokenization.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "Education Platform Development, NFT Certification, Blockchain Integration",
            "description_company_outsource": "Hedera is a Layer 1 blockchain with hashgraph technology supporting education and tokenization applications.",
        },
        {
            "company_lead_name": "Playbux",
            "industry": "Blockchain",
            "location": "Unspecified",
            "services": "DeFi Platform, Restaking, Yield Optimization",
            "project_description": "Built Vapor Fund Restaking Platform - a web3 fund platform connecting retail customers to the dynamic web3 world. Users can acquire carefully curated funds using various cryptocurrencies and stake VPR tokens to unlock rewards through earned xVPR.",
            "background": "BNB chain-based platform with support from Binance Labs. Integrates e-commerce, blockchain technology, and virtual communities with services like Shop to Earn, Walk to Earn, Watch to Earn, and Play to Earn.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "DeFi Platform Development, Staking Infrastructure, Fund Management",
            "description_company_outsource": "Playbux is a Binance Labs-backed platform offering earn-to-trade services and DeFi products.",
        },
        {
            "company_lead_name": "Fanchain",
            "industry": "Blockchain",
            "location": "Vietnam",
            "services": "NFT Marketplace, Creator Platform, Fan Engagement",
            "project_description": "Built Fanchain - a fan engagement platform unlocking a digital haven where creators and fans forge connections. Streamers, creators and influencers can create and issue NFT collections for fans to buy, sell, and trade. Viewers can support creators by donating cryptocurrency.",
            "background": "Platform designed to connect creators, influencers, and fans through tokenized communities and NFT-based engagement mechanisms.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "51-200 Employees",
            "client_min": 51,
            "client_max": 200,
            "services_company_outsource": "NFT Marketplace Development, Creator Platform, Community Building",
            "description_company_outsource": "Fanchain is a Vietnam-based creator platform enabling streamers and influencers to engage fans through NFTs and cryptocurrency.",
        },
        {
            "company_lead_name": "Bitkub",
            "industry": "AI",
            "location": "Thailand",
            "services": "Job Matching Platform, AI Matching Algorithm, Blockchain Education",
            "project_description": "Built Learn and Earn - Job Matching platform redefining the job market with blockchain and AI. Job seekers build verifiable skill portfolios through NFT-based certificates and access personalized learning. Companies can streamline hiring with verified talent pools and smart contracts.",
            "background": "Thailand's largest cryptocurrency exchange regulated by Thailand's Securities and Exchange Commission (SEC). Backed by Thailand government, focusing on innovative education and job market solutions.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "AI Development, Job Matching Algorithm, Blockchain Integration",
            "description_company_outsource": "Bitkub is Thailand's largest regulated cryptocurrency exchange offering innovative AI and blockchain solutions.",
        },
        {
            "company_lead_name": "RCVR",
            "industry": "AI",
            "location": "Unspecified",
            "services": "Data Analytics, Dispute Management, Chargeback Resolution",
            "project_description": "Built Chargeback Report Platform - an all-in-one centralized database for dispute management. Leverages advanced analytics and efficient data collection to provide comprehensive transaction details and useful indices for better business insights and data-driven decision-making.",
            "background": "Centralized platform consolidating all dispute management functionalities into one system, streamlining data analysis and making the dispute resolution process cost-effective.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "AI Analytics, Data Management, Dispute Resolution",
            "description_company_outsource": "RCVR is a dispute management platform utilizing AI and analytics for comprehensive transaction analysis.",
        },
        {
            "company_lead_name": "Peddle",
            "industry": "AI",
            "location": "Unspecified",
            "services": "AI Bidding Strategy, Data Analytics, Machine Learning",
            "project_description": "Optimized bidding strategy on Peddle online marketplace. Built real-time Tableau dashboard for transparent insights into historical bidding data. Trained ML model to predict minimum winning bid and created bidding recommender system for more effective campaigns and efficient budget allocation.",
            "background": "Online marketplace requiring optimization of bidding strategies through data analytics and machine learning to improve success rates and budget efficiency.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "51-200 Employees",
            "client_min": 51,
            "client_max": 200,
            "services_company_outsource": "AI Development, ML Model Training, Data Analytics Dashboard",
            "description_company_outsource": "Peddle is an online marketplace optimizing bidding strategies through AI and machine learning.",
        },
        {
            "company_lead_name": "Aptos",
            "industry": "AI",
            "location": "Unspecified",
            "services": "Chatbot Development, AI Integration, Developer Support",
            "project_description": "Developed automated AI chatbot to answer developer questions on Aptos Github Discussion Forum. Features configurable AI models (GPT-4o, Claude Sonnet 3.5, Move LLM), Retrieval-Augmented Generation for knowledge integration, and feedback mechanism for improving response quality.",
            "background": "Layer 1 blockchain focusing on scalability and reliability using Move programming language. Requires automated support system for developer community engagement.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "AI Chatbot Development, LLM Integration, Developer Support",
            "description_company_outsource": "Aptos is a Layer 1 blockchain providing developer tools and automated support through AI chatbots.",
        },
        {
            "company_lead_name": "AI Companion Platform",
            "industry": "AI",
            "location": "Unspecified",
            "services": "Virtual Companions, AI Assistant, Conversational AI",
            "project_description": "Built AI Companion platform allowing users to create their own virtual companions with completely unique personalities and ability to engage in deep, meaningful conversations. Functions as a digital friend for chatting, role-play, emotional support, and outlet for thoughts.",
            "background": "Platform designed to provide personalized virtual companionship and emotional support through advanced conversational AI.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "1-10 Employees",
            "client_min": 1,
            "client_max": 10,
            "services_company_outsource": "AI Development, Conversational AI, Virtual Companion Technology",
            "description_company_outsource": "AI Companion is a platform providing personalized virtual companionship through advanced conversational AI.",
        },
        {
            "company_lead_name": "0G Labs",
            "industry": "AI",
            "location": "United States",
            "services": "AI Agents, Debate Platform, Blockchain Betting",
            "project_description": "Developed AI Agents Debate platform featuring AI agents with customizable personalities, virtual debate arena, jury system with AI examiners for fairness, and blockchain-based pool betting mechanism for instant reward distribution based on debate outcomes.",
            "background": "First decentralized AI operating system backed by OG - the AI Layer 1. Enables groundbreaking AI and web3 applications with large ecosystem of decentralized AI applications.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "AI Agent Development, Debate Platform, Blockchain Integration",
            "description_company_outsource": "0G Labs is the first decentralized AI operating system backed by OG, enabling AI and web3 applications.",
        },
        {
            "company_lead_name": "4mativ",
            "industry": "AI",
            "location": "Unspecified",
            "services": "Route Optimization, Data Visualization, Process Automation",
            "project_description": "Developed school bus optimization system automating data processing, stop consolidation, and route optimization for public school transportation. Created UI allowing users to adjust parameters and view results in real-time, significantly enhancing efficiency.",
            "background": "Technology and service platform managing millions of dollars in annual transportation budgets. Helps schools save up to 40% on yearly transportation costs while improving experiences for students, families, and staff.",
            "website_outsource_url": "https://www.var-meta.com/",
            "client_size": "201-500 Employees",
            "client_min": 201,
            "client_max": 500,
            "services_company_outsource": "AI Optimization, Data Visualization, Process Automation",
            "description_company_outsource": "4mativ is a transportation management platform reducing school costs and improving experiences through AI optimization.",
        },
    ]
USER_IDS = 'https://www.var-meta.com/'