

SIZE_BUCKETS: Dict[str, Tuple[int, int]] = {
	"micro": (0, 10),
	"small": (11, 50),
	"medium": (51, 200),
	"large": (201, 1000),
	"enterprise": (1001, 10**9),
}
SIZE_MAPPING: Dict[str, List[str]] =  {
    "micro": [
        "0-1",
        "1",
        "1:5",
        "2-10",
    ],
    
    "small": [
        "11-50",
    ],
    
    "medium": [
        "51-200",
    ],
    
    "large": [
        "201-500",
        "501-1,000",
        "501-1000",
        "501-1.000",
        "500+",
    ],
    
    "enterprise": [
        "1,001-5,000",
        "1001-5000",
        "1.001-5.000",
        
        "5,001-10,000",
        "5001-10000",
        "5.001-10.000",
        
        "10,001+",
        "10.001+",
        "10,0001+",
        
        "10001",
        "10,001",
        "10.001",
        "10000",
        "10,0001",
    ]
}

INDUSTRY_MAPPING: Dict[str, List[str]] = {
    "Information technology": [
        "Software Development",
        "IT Services and IT Consulting",
        "Technology, Information and Internet",
        "Information Technology & Services",
        "Computer Games",
        "Technology, Information and Media",
        "Computer and Network Security",
        "Data Infrastructure and Analytics",
        "IT System Custom Software Development",
        "Semiconductor Manufacturing",
        "IT System Data Services",
        "Embedded Software Products",
        "Mobile Computing Software Products",
        "Desktop Computing Software Products",
        "Computer Networking Products",
        "IT System Design Services",
        "IT System Operations and Maintenance",
        "IT System Testing and Evaluation",
        "Computer Hardware Manufacturing",
        "Computer Hardware",
        "Computer Networking",
        "Computers and Electronics Manufacturing",
        "Wireless Services",
        "IT System Training and Support",
    ],
    "Real estate": [
        "Real Estate",
        "Leasing Non-residential Real Estate",
        "Leasing Residential Real Estate",
        "Real Estate Agents and Brokers",
        "Real Estate and Equipment Rental Services",
        "Commercial Real Estate",
    ],
    "Financial services": [
        "Financial Services",
        "Venture Capital and Private Equity Principals",
        "Investment Management",
        "Capital Markets",
        "Investment Banking",
        "Investment Advice",
        "Securities and Commodity Exchanges",
        "Funds and Trusts",
    ],
    "Insurance": [
        "Insurance",
        "Insurance Agencies and Brokerages",
        "Insurance and Employee Benefit Funds",
    ],
    "Advertising & marketing": [
        "Advertising Services",
        "Marketing Services",
        "Public Relations and Communications Services",
    ],
    "Education": [
        "Education",
        "E-Learning Providers",
        "E-learning",
        "Higher Education",
        "Primary and Secondary Education",
        "Education Administration Programs",
        "Education Management",
        "Language Schools",
        "Technical and Vocational Training",
        "Fine Arts Schools",
    ],
    "Manufacturing": [
        "Manufacturing",
        "Medical Equipment Manufacturing",
        "Defense and Space Manufacturing",
        "Automation Machinery Manufacturing",
        "Pharmaceutical Manufacturing",
        "Motor Vehicle Manufacturing",
        "Semiconductor Manufacturing",
        "Appliances, Electrical, and Electronics Manufacturing",
        "Industrial Machinery Manufacturing",
        "Chemical Manufacturing",
        "Computers and Electronics Manufacturing",
        "Machinery Manufacturing",
        "Beverage Manufacturing",
        "Apparel Manufacturing",
        "Sporting Goods Manufacturing",
        "Textile Manufacturing",
        "Paper and Forest Product Manufacturing",
        "Plastics Manufacturing",
        "Electrical Equipment Manufacturing",
        "Motor Vehicle Parts Manufacturing",
        "Food and Beverage Manufacturing",
        "Personal Care Product Manufacturing",
        "Renewable Energy Equipment Manufacturing",
        "Packaging and Containers Manufacturing",
        "Beverage Manufacturing",
        "Dairy Product Manufacturing",
        "Agricultural Chemical Manufacturing",
        "HVAC and Refrigeration Equipment Manufacturing",
        "Paint, Coating, and Adhesive Manufacturing",
        "Chemical Raw Materials Manufacturing",
        "Electric Lighting Equipment Manufacturing",
        "Engines and Power Transmission Equipment Manufacturing",
        "Metalworking Machinery Manufacturing",
        "Office Furniture and Fixtures Manufacturing",
        "Plastics and Rubber Product Manufacturing",
        "Sugar and Confectionery Product Manufacturing",
        "Audio and Video Equipment Manufacturing",
        "Communications Equipment Manufacturing",
        "Engines and Power Transmission Equipment Manufacturing",
        "Fashion Accessories Manufacturing",
        "Footwear Manufacturing",
        "Fuel Cell Manufacturing",
        "Glass Product Manufacturing",
        "Household Appliance Manufacturing",
        "Measuring and Control Instrument Manufacturing",
        "Motor Vehicle Parts Manufacturing",
        "Railroad Equipment Manufacturing",
        "Smart Meter Manufacturing",
        "Tobacco Manufacturing",
        "Wood Product Manufacturing",
        "Apparel Manufacturing",
        "Animal Feed Manufacturing",
        "Architectural and Structural Metal Manufacturing",
        "Textile Manufacturing",
        "Household Appliance Manufacturing",
    ],
    "Hospitality & leisure": [
        "Hospitality",
        "Hotels and Motels",
        "Restaurants",
        "Food and Beverage Services",
        "Travel Arrangements",
        "Leisure, Travel & Tourism",
        "Amusement Parks and Arcades",
        "Recreational Facilities",
    ],
    "Medical": [
        "Hospitals and Health Care",
        "Medical Equipment Manufacturing",
        "Medical Device",
        "Medical Practices",
        "Mental Health Care",
        "Medical and Diagnostic Laboratories",
        "Dentists",
        "Pharmaceutical Manufacturing",
        "Health, Wellness & Fitness",
        "Wellness and Fitness Services",
        "Home Health Care Services",
        "Individual and Family Services",
        "Health and Human Services",
        "Alternative Medicine",
        "Public Health",
    ],
    "Retail": [
        "Retail",
        "Retail Apparel and Fashion",
        "Retail Luxury Goods and Jewelry",
        "Retail Office Equipment",
        "Retail Health and Personal Care Products",
        "Online and Mail Order Retail",
        "Retail Motor Vehicles",
        "Retail Groceries",
        "Food and Beverage Retail",
        "Retail Furniture and Home Furnishings",
        "Retail Appliances, Electrical, and Electronic Equipment",
        "Retail Pharmacies",
        "Retail Art Supplies",
        "Retail Art Dealers",
        "Retail Office Supplies and Gifts",
        "Retail Recyclable Materials & Used Merchandise",
    ],
    "Construction": [
        "Construction",
        "Building Construction",
        "Residential Building Construction",
        "Building Equipment Contractors",
        "Building Structure and Exterior Contractors",
        "Specialty Trade Contractors",
        "Highway, Street, and Bridge Construction",
        "Community Development and Urban Planning",
    ],
    "Telecommunications": [
        "Telecommunications",
        "Telecommunications Carriers",
        "Telephone Call Centers",
        "Satellite Telecommunications",
        "Wireless Services",
        "Media and Telecommunications",
    ],
    "Arts, entertainment & music": [
        "Entertainment Providers",
        "Entertainment",
        "Media Production",
        "Online Audio and Video Media",
        "Movies, Videos, and Sound",
        "Music",
        "Musicians",
        "Performing Arts",
        "Animation and Post-production",
        "Animation",
        "Artists and Writers",
        "Photography",
        "Design Services",
        "Design",
        "Graphic Design",
        "Fine Art",
        "Arts & Crafts",
        "Performing Arts and Spectator Sports",
    ],
    "Legal": [
        "Law Practice",
        "Legal Services",
    ],
    "Gaming": [
        "Computer Games",
        "Mobile Gaming Apps",
        "Gambling Facilities and Casinos",
    ],
    "Media": [
        "Internet Publishing",
        "Media Production",
        "Online Audio and Video Media",
        "Broadcast Media Production and Distribution",
        "Online Media",
        "Internet News",
        "Newspaper Publishing",
        "Book and Periodical Publishing",
        "Book Publishing",
        "Movies, Videos, and Sound",
        "Radio and Television Broadcasting",
        "Business Content",
        "Blogs",
    ],
    "Automotive": [
        "Automotive",
        "Motor Vehicle Manufacturing",
        "Retail Motor Vehicles",
    ],
    "Energy & natural resources": [
        "Oil and Gas",
        "Services for Renewable Energy",
        "Renewable Energy Power Generation",
        "Renewable Energy Semiconductor Manufacturing",
        "Coal Mining",
        "Metal Ore Mining",
        "Mining",
        "Environmental Services",
        "Electric Power Generation",
        "Electric Power Transmission, Control, and Distribution",
        "Solar Electric Power Generation",
        "Geothermal Electric Power Generation",
        "Wind Electric Power Generation",
        "Nuclear Electric Power Generation",
        "Energy Technology",
        "Climate Data and Analytics",
        "Climate Technology Product Manufacturing",
        "Renewables & Environment",
    ],
    "Food & Beverage": [
        "Food and Beverage Services",
        "Restaurants",
        "Food and Beverage Manufacturing",
        "Food and Beverage Retail",
        "Food Production",
        "Beverage Manufacturing",
        "Caterers",
        "Mobile Food Services",
        "Wine & Spirits",
        "Wineries",
        "Wholesale Food and Beverage",
        "Wholesale Alcoholic Beverages",
    ],
    "Non-profit": [
        "Non-profit Organizations",
        "Non-profit Organization Management",
    ],
    "Government": [
        "Government Administration",
        "Public Safety",
        "Public Policy",
        "Government Relations Services",
        "Public Policy Offices",
        "Government Relations",
        "Law Enforcement",
    ],
    "Business services": [
        "Business Consulting and Services",
        "Business Intelligence Platforms",
        "Strategic Management Services",
        "Operations Consulting",
        "Professional Services",
        "Professional Training and Coaching",
        "Executive Search Services",
        "Staffing and Recruiting",
        "Outsourcing and Offshoring Consulting",
        "Outsourcing/Offshoring",
        "Human Resources Services",
        "Human Resources",
    ],
    "Supply Chain, Logistics, and Transport": [
        "Transportation, Logistics, Supply Chain and Storage",
        "Truck Transportation",
        "Airlines and Aviation",
        "Freight and Package Transportation",
        "Urban Transit Services",
        "Rail Transportation",
        "Maritime Transportation",
        "Ground Passenger Transportation",
        "Taxi and Limousine Services",
        "Warehousing and Storage",
        "Warehousing",
        "Logistics",
    ],
    "Sports": [
        "Spectator Sports",
        "Sports Teams and Clubs",
        "Sports and Recreation Instruction",
    ],
    "Contracting": [
        "Building Equipment Contractors",
        "Building Structure and Exterior Contractors",
        "Specialty Trade Contractors",
    ],
    "Utilities": [
        "Utilities",
        "Utilities Administration",
    ],
    "Banks": [
        "Banking",
    ],
    "Gambling": [
        "Gambling Facilities and Casinos",
    ],
    "Consumer products & services": [
        "Consumer Services",
        "Consumer Goods",
        "Consumer Electronics",
        "Consumer Goods Rental",
    ],
    "HVAC": [
        "HVAC and Refrigeration Equipment Manufacturing",
    ],
    "Dental": [
        "Dentists",
    ],
    "Beauty": [
        "Personal Care Services",
    ],
    "Fitness": [
        "Wellness and Fitness Services",
        "Health, Wellness & Fitness",
    ],
    "Legal Cannabis": [
    ],
    "Politics": [
        "Political Organizations",
    ],
    "Roofing": [
    ],
    "Cleaners": [
    ],
    "GPS, Navigation & GIS": [
    ],
    "Recreation": [
        "Amusement Parks and Arcades",
        "Recreational Facilities",
    ],
    "Electric": [
        "Electric Power Generation",
        "Electric Power Transmission, Control, and Distribution",
        "Solar Electric Power Generation",
        "Geothermal Electric Power Generation",
        "Wind Electric Power Generation",
        "Nuclear Electric Power Generation",
    ],
    "Home Services": [
        "Home Health Care Services",
        "Household Services",
        "Interior Design",
        "Landscaping Services",
    ],
    "eCommerce": [
        "Internet Marketplace Platforms",
    ],
}