DEFAULT_MAP_ACTOR_TO_ID = {
    "LINKEDIN_GET_LEADS": "T1XDXWc1L92AfIJtd",
    "LINKEDIN_GET_PROFILE_PERSON": "LpVuK3Zozwuipa5bp",
    "LINKEDIN_GET_POST": "Wpp1BZ6yGWjySadk3",
    "LINKEDIN_GET_JOB": "JkfTWxtpgfvcRQn3p",
    "LINKEDIN_GET_ONLY_EMAIL" : "q3wko0Sbx6ZAAB2xf",
    "LINKEDIN_GET_EMAIL_AND_PROFILE" : "GOvL4O4RwFqsdIqXF"
}
