INDUSTRIES_REJECT = ['Staffing and Recruiting',
                    'Human Resources Services',
                    'Executive Search Services',
                    'Outsourcing/Offshoring',
                    'Professional Services',
                    'Business Consulting and Services',
                    'Professional Training and Coaching',
                    'Human Resources',
                    'Executive Offices',
                    'Operations Consulting',
                    'Venture Capital and Private Equity Principals',
                    'Investment Management',
                    'Capital Markets',
                    'Investment Banking'
                    ]
KEY_WORDS = ["Blockchain", "AI"]
LOCATIONS = ["US", "UK", "Canada", "Taiwan", "Singapore", "Malaysia", "Thailand", "Hong Kong", "Australia", "Netherland", "Finland", "Switzerland", "Korea"]
IMPORTANT_KEYS = ["ai",
                "artificial intelligence",
                "machine learning",
                "natural language",
                "deep learning",
                "deep reinforcement",
                "scientist",
                "computer vision",
                "quantitative",
                "web3",
                "blockchain",
                "ai/ml",
                "smart contract",
                "web3",
                "token",
                "solidity",
                "polkadot",
                "develop",
                "engineer",
                "contract",
                "lead",
                "head "
                ]